# Generated by Django 3.2.6 on 2021-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='wdo_book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ativo', models.CharField(default='null', max_length=6)),
                ('dia', models.DateField()),
                ('hora', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quantidade', models.PositiveIntegerField()),
                ('comprador', models.PositiveIntegerField()),
                ('vendedor', models.PositiveIntegerField()),
                ('agressor', models.CharField(choices=[('C', 'Comprador'), ('V', 'Vendedor'), ('L', 'Leilao')], default='L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='win_book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ativo', models.CharField(max_length=6)),
                ('dia', models.DateField()),
                ('hora', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quantidade', models.PositiveIntegerField()),
                ('comprador', models.PositiveIntegerField()),
                ('vendedor', models.PositiveIntegerField()),
                ('agressor', models.CharField(choices=[('C', 'Comprador'), ('V', 'Vendedor'), ('L', 'Leilao')], default='L', max_length=1)),
            ],
        ),
    ]
