# Generated by Django 3.2.6 on 2021-08-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratofuturo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Atual'), (2, 'Vencido'), (3, 'Proximo')], default=2, help_text='...'),
        ),
    ]
