# Generated by Django 3.2.6 on 2021-08-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_contratofuturo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoFuturoDolar',
            fields=[
                ('ticket', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('vencimento_dt', models.DateField()),
                ('vencimento', models.CharField(choices=[('F', 'Janeiro'), ('G', 'Fevereiro'), ('H', 'Marco'), ('J', 'Abril'), ('K', 'Maio'), ('M', 'Junho'), ('N', 'Julho'), ('Q', 'Agosto'), ('U', 'Setembro'), ('V', 'Outubro'), ('X', 'Novembro'), ('Z', 'Dezembro')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoFuturoIndice',
            fields=[
                ('ticket', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('vencimento_dt', models.DateField()),
                ('vencimento', models.CharField(choices=[('G', 'Fevereiro'), ('J', 'Abril'), ('M', 'Junho'), ('Q', 'Agosto'), ('V', 'Outubro'), ('Z', 'Dezembro')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContratoFuturo',
        ),
    ]
