# Generated by Django 3.2.6 on 2021-08-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_auto_20210805_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False)),
                ('hora', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quantidade', models.PositiveIntegerField()),
                ('comprador', models.PositiveIntegerField()),
                ('vendedor', models.PositiveIntegerField()),
                ('agressor', models.CharField(choices=[('C', 'Comprador'), ('V', 'Vendedor'), ('L', 'Leilao')], max_length=1)),
            ],
        ),
    ]
