# Generated by Django 3.2.6 on 2021-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_corretora_negocio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratoFuturoDolar',
            new_name='WDO',
        ),
        migrations.RenameModel(
            old_name='ContratoFuturoIndice',
            new_name='WIN',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
