# Generated by Django 3.2.6 on 2021-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_auto_20210806_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretora',
            name='color',
            field=models.CharField(default=11544, max_length=6),
            preserve_default=False,
        ),
    ]
