# Generated by Django 3.2.6 on 2021-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0007_wdo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='status',
            field=models.CharField(choices=[('1', 'Vencido'), ('2', 'Atual')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
